<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('users')->upsert([
            // Admin
            [
                'id'                => 1,
                'email'             => 'admin@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Administrator SBA',
                'phone_number'      => '081234567801',
                'role'              => 'admin',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // Finance
            [
                'id'                => 2,
                'email'             => 'finance@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Budi Santoso',
                'phone_number'      => '081234567802',
                'role'              => 'finance',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 3,
                'email'             => 'finance2@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Dewi Rahayu',
                'phone_number'      => '081234567803',
                'role'              => 'finance',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // Customer Service
            [
                'id'                => 4,
                'email'             => 'cs1@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Andi Pratama',
                'phone_number'      => '081234567804',
                'role'              => 'cs',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 5,
                'email'             => 'cs2@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Siti Nurhaliza',
                'phone_number'      => '081234567805',
                'role'              => 'cs',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 6,
                'email'             => 'cs3@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Rizky Firmansyah',
                'phone_number'      => '081234567806',
                'role'              => 'cs',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 7,
                'email'             => 'cs4@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Maya Anggraini',
                'phone_number'      => '081234567807',
                'role'              => 'cs',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 8,
                'email'             => 'cs5@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Hendra Kusuma',
                'phone_number'      => '081234567808',
                'role'              => 'cs',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 9,
                'email'             => 'cs6@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Fitri Handayani',
                'phone_number'      => '081234567809',
                'role'              => 'cs',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 10,
                'email'             => 'cs7@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Agus Setiawan',
                'phone_number'      => '081234567810',
                'role'              => 'cs',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 11,
                'email'             => 'cs8@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Rina Oktavia',
                'phone_number'      => '081234567811',
                'role'              => 'cs',
                'status'            => 'inactive',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 12,
                'email'             => 'cs9@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Bayu Wicaksono',
                'phone_number'      => '081234567812',
                'role'              => 'cs',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 13,
                'email'             => 'cs10@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Lestari Widodo',
                'phone_number'      => '081234567813',
                'role'              => 'cs',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 14,
                'email'             => 'cs11@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Doni Kurniawan',
                'phone_number'      => '081234567814',
                'role'              => 'cs',
                'status'            => 'inactive',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 15,
                'email'             => 'cs12@sbalogistik.test',
                'password'          => Hash::make('password'),
                'full_name'         => 'Yuni Astuti',
                'phone_number'      => '081234567815',
                'role'              => 'cs',
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ], ['id'], ['email', 'password', 'full_name', 'phone_number', 'role', 'status', 'email_verified_at', 'updated_at']);
    }
}
